name: UMG QA

on:
  push:
    paths:
      - '**.py'
      - 'blocks/**.json'
      - 'memory/overlays/**.json'
  pull_request:
  workflow_dispatch:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (none required)
        run: echo "No pip deps for stubs"

      - name: Validate blocks
        run: python validate_blocks.py

      - name: Repair registry
        run: python repair_registry.py
